### ISSUE TITLE
Duplicate stress message 

### ISSUE THREAD

**Issue by NicolasGrosjean** [cybrxkhan/RICE-for-CK3#111]
In `activity_RICE_rhodes_visit_to_the_colossus_guest_desc`, there is twice `$BULLET_WITH_TAB$Lose [stress_loss_i|E][stress|E]`.

I don't know how to fix it (if it is a copy-paste error and something is missing : piety ?)

**Comment by cybrxkhan** [comment]
Yeah, I think you're right, thanks for the heads up. Just catching up on all the stuff you've sent over in the past couple weeks now. Thanks for the correction and for all the other fixes and translations!
