### ISSUE TITLE
Question about Sicily

### ISSUE THREAD

**Issue by FerchuDev** [cybrxkhan/RICE-for-CK3#129]
These four entries are empty:
RICE_sicily_struggle_ending_dominion_latin_desc: ""
RICE_sicily_struggle_ending_dominion_greek_desc: ""
RICE_sicily_struggle_ending_dominion_arabic_desc: "" 
RICE_sicily_struggle_ending_dominion_outsider_desc: ""

Is this correct?

And this one?:
game_concept_RICE_sicily_struggle_desc:2 "I'll make you an offer you can't refuse."

**Comment by cybrxkhan** [comment]
The four empty entries are correct, but the last one, the game concept for the Sicilian struggle, is not (that's the placeholder text) - thanks for the heads up on that! I'll fix that last one shortly. Thanks!
