### ISSUE TITLE
RICE utf8-bom bug

### ISSUE THREAD

**Issue by Juijote** [cybrxkhan/RICE-for-CK3#17]
File 'music/aachen_flavor_pack_music.txt' should be in utf8-bom encoding (will try to use it anyways)
File 'music/harran_flavor_pack.txt' should be in utf8-bom encoding (will try to use it anyways)
File 'music/tuyuhun_flavor_pack_music.txt' should be in utf8-bom encoding (will try to use it anyways)
File 'music/zz_ck2_music.txt' should be in utf8-bom encoding (will try to use it anyways)

**Comment by cybrxkhan** [comment]
Ok thanks for heads up! I'll fix that.
