### ISSUE TITLE
About the Shahis and white huns

### ISSUE THREAD

**Issue by hyrathon** [cybrxkhan/RICE-for-CK3#82]
When browsing CK3 wiki, I found something interesting:
https://ck3.paradoxwikis.com/Interesting_characters#Kabulistan
https://en.wikipedia.org/wiki/Hindu_Shahis
It seems the Shahis are of white huns origin, which is suitable for your Zunbil content pack. Could you please reflect this in your content pack to make them more immersive?

**Comment by cybrxkhan** [comment]
Hi there! The Turkishahis likely have some connections with the post-imperial White Huns/Hephthalites, but the later Hindushahis, who are present in the 867 start date are different from the Turkishahis as they overthrew the original Turkishahis in some manner. It's harder to say who they exactly were, based on my extensive research into the region I made previously, so I didn't make them Turco-Hephthalite. As an aside, if I ever do a proper Afghan update, I'll definitely add in some unique flavor for the Hindushahis regardless.
