### ISSUE TITLE
Canary Islands/Guanche CFP incompatibility

### ISSUE THREAD

**Issue by countduckulawasbad** [cybrxkhan/RICE-for-CK3#83]
When I start as a ruler in 867, if you click on the Canary Islands or look at any of the Canary island rulers/their family the game instantly CTD. 

Both CFP and RICE work individually, and both are fully updated (my game is updated to 1.10.2, but it also didn't work on 1.10.0). This happens in a new game + the game I progressed for about 40 years until I crashed because I wanted to conquer the Canaries

Guanche people are fine but even looking at nearby rulers on the search instantly CTD because it loads a Canary Island ruler. If I just could ignore the Canary rulers it would be fine but I have to tweak my search just to make sure they don't show up.

**Comment by countduckulawasbad** [comment]
Force-reinstalled CFP after different crash in Africa and all seems fixed, thanks a lot Steam Workshop 
Sorry for any trouble😔

**Comment by cybrxkhan** [comment]
No worries, glad you figured it out!
